# ~/.tmuxinator/dev.yml

name: dev
root: ~/all/repo

# Runs before everything. Use it to start daemons etc.
# pre: systemctl start docker

# Specifies (by name or index) which window will be selected on project startup
startup_window: home

windows:
  - home:
      layout: main-horizontal
      panes:
        - # blank
        - # blank
  - editor:
      layout: main-vertical
      panes:
        - jc hacktiv8
        - jc hacktiv8
  - extra: # blank

